AWSTemplateFormatVersion: "2010-09-09"
Description: Auto Scaling Apache Web Server with ALB and CPU-based Scaling

Parameters:
  VpcCidr:
    Type: String
    Default: 10.20.0.0/16

  PublicSubnetCidr:
    Type: String
    Default: 10.20.1.0/24

  PublicSubnet2Cidr:
    Type: String
    Default: 10.20.3.0/24

  PrivateSubnetCidr:
    Type: String
    Default: 10.20.2.0/24

  PrivateSubnet2Cidr:
    Type: String
    Default: 10.20.4.0/24

  AmiId:
    Type: String
    Description: AMI ID for EC2 instances
    Default: ami-02b7d5b1e55a7b5f1

  LabTagValue:
    Type: String
    Default: week3_lab1

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: AutoScalingLabVPC
        - Key: lab
          Value: !Ref LabTagValue

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: lab
          Value: !Ref LabTagValue

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref PublicSubnetCidr
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select [0, !GetAZs ""]
      Tags:
        - Key: lab
          Value: !Ref LabTagValue

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref PublicSubnet2Cidr
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select [1, !GetAZs ""]
      Tags:
        - Key: lab
          Value: !Ref LabTagValue

  PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref PrivateSubnetCidr
      AvailabilityZone: !Select [0, !GetAZs ""]
      Tags:
        - Key: lab
          Value: !Ref LabTagValue

  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref PrivateSubnet2Cidr
      AvailabilityZone: !Select [1, !GetAZs ""]
      Tags:
        - Key: lab
          Value: !Ref LabTagValue

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: lab
          Value: !Ref LabTagValue

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PublicSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet
      RouteTableId: !Ref PublicRouteTable

  PublicSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet2
      RouteTableId: !Ref PublicRouteTable

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP access from ALB
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          SourceSecurityGroupId: !Ref LoadBalancerSecurityGroup
      Tags:
        - Key: lab
          Value: !Ref LabTagValue

  LoadBalancerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP from internet
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: lab
          Value: !Ref LabTagValue

  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        ImageId: !Ref AmiId
        InstanceType: t2.micro
        SecurityGroupIds:
          - !Ref InstanceSecurityGroup
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash -xe
            yum update -y
            yum install -y httpd stress
            sed -i '/^#LoadModule cgi_module modules\/mod_cgi.so/s/^#//' /etc/httpd/conf.modules.d/00-base.conf
            mkdir -p /var/www/cgi-bin
            chown apache:apache /var/www/cgi-bin
            systemctl start httpd
            systemctl enable httpd
            INSTANCE_ID=$(curl -s http://169.254.169.254/latest/meta-data/instance-id)
            IP=$(curl -s http://169.254.169.254/latest/meta-data/local-ipv4)
            cat <<EOF > /var/www/html/index.html
            <!DOCTYPE html>
            <html>
            <head>
              <title>Auto Scaling Lab</title>
              <style>
                body { font-family: Arial; text-align: center; margin-top: 50px; }
                button { padding: 10px 20px; font-size: 14px; }
              </style>
            </head>
            <body>
              <h1>Hello from $IP / $INSTANCE_ID</h1>
              <p>This instance is auto-scaled.</p>
              <button onclick="stressCPU()">Stress CPU</button>
              <script>
                function stressCPU() {
                  fetch('/cgi-bin/stress-cpu', { method: 'POST' })
                    .then(() => alert('CPU stress triggered!'))
                    .catch(err => alert('Error: ' + err));
                }
              </script>
            </body>
            </html>
            EOF
            cat <<EOF > /var/www/cgi-bin/stress-cpu
            #!/bin/bash
            echo "Content-type: text/html"
            echo ""
            echo "<html><body><h3>CPU stress started...</h3></body></html>"
            nohup stress --cpu 2 --timeout 60 >/dev/null 2>&1 &
            EOF
            chmod +x /var/www/cgi-bin/stress-cpu
            if ! grep -q "<Directory \"/var/www/cgi-bin\">" /etc/httpd/conf/httpd.conf; then
              cat <<CGI >> /etc/httpd/conf/httpd.conf
            <Directory "/var/www/cgi-bin">
                AllowOverride None
                Options +ExecCGI
                Require all granted
                AddHandler cgi-script .cgi .sh
            </Directory>
            CGI
              systemctl restart httpd
            fi
      TagSpecifications:
        - ResourceType: launch-template
          Tags:
            - Key: lab
              Value: !Ref LabTagValue

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !Ref VPC
      Port: 80
      Protocol: HTTP
      TargetType: instance
      HealthCheckPath: /
      Tags:
        - Key: lab
          Value: !Ref LabTagValue

  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: AutoScalingALB
      Subnets:
        - !Ref PublicSubnet
        - !Ref PublicSubnet2
      SecurityGroups:
        - !Ref LoadBalancerSecurityGroup
      Scheme: internet-facing
      Type: application
      Tags:
        - Key: lab
          Value: !Ref LabTagValue

  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup
      LoadBalancerArn: !Ref LoadBalancer
      Port: 80
      Protocol: HTTP

  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier:
        - !Ref PrivateSubnet
        - !Ref PrivateSubnet2
      MinSize: "1"
      MaxSize: "3"
      DesiredCapacity: "1"
      TargetGroupARNs:
        - !Ref TargetGroup
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplate
        Version: !GetAtt LaunchTemplate.LatestVersionNumber
      HealthCheckType: ELB
      HealthCheckGracePeriod: 300
      Tags:
        - Key: lab
          Value: !Ref LabTagValue
          PropagateAtLaunch: true
        - Key: Name
          Value: AutoScalingInstance
          PropagateAtLaunch: true

  ScaleOutPolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    Metadata:
      Description: "Scale out policy to add instances when average CPU > 50%"
    Properties:
      AutoScalingGroupName: !Ref AutoScalingGroup
      PolicyType: TargetTrackingScaling
      Cooldown: 60
      TargetTrackingConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: ASGAverageCPUUtilization
        TargetValue: 50.0
        DisableScaleIn: false

  ScaleInPolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    Metadata:
      Description: "Scale in policy to remove instances when average CPU < 20%"
    Properties:
      AutoScalingGroupName: !Ref AutoScalingGroup
      PolicyType: TargetTrackingScaling
      Cooldown: 60
      TargetTrackingConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: ASGAverageCPUUtilization
        TargetValue: 20.0
        DisableScaleIn: false

Outputs:
  LoadBalancerDNS:
    Description: ALB DNS Name
    Value: !GetAtt LoadBalancer.DNSName
